site_name: AeroKit
repo_name: aerokit
repo_url: https://github.com/jgressier/aerokit

theme:
  name: material
  icon:
    repo: fontawesome/brands/github

nav:
  - Home: index.md
  - User Guide: userguide.md
  - About: about.md

plugins:
  - search