site_name: AeroKit
repo_name: aerokit
repo_url: https://github.com/jgressier/aerokit
edit_uri: ''  #disables edit button

theme:
  name: material
  icon:
    repo: fontawesome/brands/github
  # language: en
  # features:
  #   - navigation.tabs

nav:
  - Home: index.md
  - User Guide: userguide.md
  - Examples: 
    - Examples: examples.md
    - aero.Isentropic: examples/aero.Isentropic.ipynb
  - Change log: changelog.md
  - About: about.md

plugins:
  - search
  - include-markdown
  - mkdocs-jupyter:
      execute: True
      include_source: False
  - exclude:
      glob:
        - "requirements.txt"
        - "*/.ipynb_checkpoints"