[tool.poetry]
name = "aerokit"
version = "1.0.0"
description = "Python tools for basic fluid mechanics computations"
authors = ["j.gressier <jeremie.gressier@isae-supaero.fr>"]
repository = ""
documentation = ""
license = "MIT"
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Intended Audience :: Science/Research",
    "Topic :: Scientific/Engineering :: Physics",
    "Topic :: Software Development :: Libraries :: Python Modules"
exclude = [ "notebooks", "gallery" ]

[tool.poetry.dependencies]
python = "*"
numpy = "^1.19.4"
scipy = "^1.5.4"
matplotlib = "^3.3.3"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
# build-backend = "poetry.core.masonry.api"

[tool.pytest.ini_options]
minversion = "6.0"
addopts = "--cov -v"
testpaths = [
    "tests"
]
