[tool.poetry]
name = "hades"
version = "0.1.0"
description = "Python tools for fluid mechanics computations"
authors = ["j.gressier <jeremie.gressier@isae.fr>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.5"
numpy = "^1.19.4"
scipy = "^1.5.4"
matplotlib = "^3.3.3"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
